import { UserProvider } from '@/contexts/user_provider'
import './globals.css'
import React from 'react'

export const metadata = {
  title: 'Template Clean Architecture Frontend',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  )
}
