name: aws_cd

on:
  push:
    branches:
      - dev
      - create-cd

jobs:
  DeployToAWS:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v2
        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

        - name: Setting stage and stack name
          run: |
            echo "STAGE=${{ github.ref_name }}" 
            echo "STACK_NAME=PortalInternoStackFront${{github.ref_name}}" >> $GITHUB_ENV

        - uses: actions/checkout@v3

        - name: Installing Dependencies
          run: |
            npm install -g aws-cdk
            npm install -g typescript
            npm install -g
            cd iac
            npm install

        - name: DeployWithCDK
          run: |
            cd iac
            cdk synth
            cdk deploy --require-approval never 

          env:
              AWS_REGION: ${{ vars.AWS_REGION }}
              AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
              STACK_NAME: ${{ env.STACK_NAME }}
              GITHUB_REF_NAME: ${{ github.ref_name }}