name: React.js CI

on:
  push:
    branches:
      - dev
      - homolog
      - prod
  pull_request:
    branches:
      - dev
      - homolog
      - prod
jobs:
  next_js_ci:
    name: Run React.js CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Build React.js app
        run: yarn build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
